### PR TITLE
Test

### PR DESCRIPTION
**Pull request by mariobarrioss**
We implemented a test suite using jest for the following modules:

- localStorage module
- Project class module
- Todo class module

### CODE REVIEW

**Review by wathigo — CHANGES_REQUESTED** [review]
# Changes Required :o: 
Great job on this milestone.

## REQUIRED
* All functions should be tested. The functions `storeProjectList` and `checkDefaultProject` in `localStorage` module are yet to be tested.
* Let's update the README file with information on how to run tests.

**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

**Comment by mariobarrioss** [comment]
The following changes were implemented as required by code review:

- Added tests for storeProjectList() and checkDefaultProject() in localStorage module.
- Updated the README file with information on how to run tests.

**Review by elmejdki — APPROVED** [review]
# status: approved :heavy_check_mark: 

Great job @team, thanks for making the required changes by the previous TSE.

now you can merge your project is approved.

## Happy Coding :tophat:

**Comment by mariobarrioss** [comment]
Thanks @wathigo and @elmejdki for the prompt reviews.

**Pull request merged**
